### ISSUE TITLE
when you can, can you add more items to the list.

### ISSUE THREAD

**Issue by ATheMorning** [Ariescyn/EldenRing-Save-Manager#14]
I was wondering if you can add items like the gold pickled fowl foot, silver pickled fowl foot, cracked pots, and other crafting items to the item editor. If you need it this has a list of all known hexes and IDs of some items: https://docs.google.com/spreadsheets/d/1c7rIV3bBKDxP9ngixgigd7ZmczH3DYhDmMt8HY4ijV0/edit?usp=sharing

**Comment by Ariescyn** [comment]
Those are in-memory hex addresses, which is different than manipulating save data. 
Can you give me a list of the most important crafting items and I'll add them

**Comment by ATheMorning** [comment]
Non-crafting: **Gold pickled fowl foot**, silver pickled fowl foot
Crafting: **Cracked pot, thin beast bones**(for arrows), **perfume bottles**, flight pinion(for fletched arrows), four toes fowl foot, gold fireflies, root resin, and bewitching branches(to help with Commander Niall)

Sorry for taking so long to reply(btw the ones in bold are the most important ones the others are more of a luxury)

**Comment by Ariescyn** [comment]
I can send you a script that automates most the work. You'd just have to duplicate a save file, change values, then run the script and it will print out the item id

**Comment by ATheMorning** [comment]
May I see the script too. I would like to see how it works

**Comment by Ariescyn** [comment]
https://github.com/Ariescyn/EldenRing-Save-Manager/blob/Testing/item_finder.py

**Comment by ludanin** [comment]
> Unfortunately those are in-memory hex addresses, which is different than manipulating save data. Can you give me a list of the most important crafting items and I'll add them

Apparently some of the IDs in this list are abstractions over the byte addresses found on your code, for example [Golden Rune [1]](https://docs.google.com/spreadsheets/d/1c7rIV3bBKDxP9ngixgigd7ZmczH3DYhDmMt8HY4ijV0/edit#gid=426973583&range=A248) has the id 2900 which represented by bytes as `84 + (11*256)`

https://github.com/Ariescyn/EldenRing-Save-Manager/blob/c9b40ec037fcc8193c3bc18e8204850c5cd45117/itemdata.py#L26

The same will be true for [Somber Smithing Stone [1]](https://docs.google.com/spreadsheets/d/1c7rIV3bBKDxP9ngixgigd7ZmczH3DYhDmMt8HY4ijV0/edit#gid=426973583&range=A862), `10160 == 176 + (39*256)`

https://github.com/Ariescyn/EldenRing-Save-Manager/blob/c9b40ec037fcc8193c3bc18e8204850c5cd45117/itemdata.py#L14

---------

It's been a super while since I've coded in Python, but I wanna check if I can try to see if we can add items without having them in the inventory -- cause I'm wasn't aware bell bearings wouldn't be carried over to NG+ and gosh I'm super lazy x.x

**Comment by ludanin** [comment]
> It's been a super while since I've coded in Python, but I wanna check if I can try to see if we can add items without having them in the inventory -- cause I'm wasn't aware bell bearings wouldn't be carried over to NG+ and gosh I'm super lazy x.x

I think that's possible as long as players take [Tarnished's Wizened Finger](https://eldenring.wiki.fextralife.com/Tarnished's+Wizened+Finger) at the beginning of their playthrough, my suggestion is that in case we can't find the index for the item at `hex.additem` then we could just append after the finger index

I'll check if this idea works later today when I'm back home, if it does I'll open a PR for this + the upgrade bell bearings that I want

**Comment by ludanin** [comment]
Adding an item seems trickier than I thought since the game save files are of a static size, which makes sense, although there's a lot of zero bytes laying around on the file and that apparently after every item there's a three `0` I'm not too confident on trying to replace any trailing 0 in fear of breaking files.

But one thing that I noticed is that we can easily replace any item in the inventory, for example I had replaced crafting materials like rowa fruit with the stuff I needed:

![2022-05-29 12-59-18](https://user-images.githubusercontent.com/31702297/170879151-7a30b250-774e-4d38-ae7f-27a1074b7e96.png)

Do u think it's worth adding this as a feature?

**Comment by Ariescyn** [comment]
Hey thanks for looking into this! Will all hex IDs from the list that atthemoring posted work? I actually already have the functionality built to replace items but haven't incorporated it into the project yet.

**Comment by ludanin** [comment]
> Hey thanks for looking into this! Will all hex IDs from the list that atthemoring posted work? I actually already have the functionality built to replace items but haven't incorporated it into the project yet.

np :raised_hands:! The hex ids will probably not work, but the sheet has decimal ids which seems to be working, my only concern is that some of them are too big to fit in 3 bytes, like [Pest's Glaive](https://docs.google.com/spreadsheets/d/1c7rIV3bBKDxP9ngixgigd7ZmczH3DYhDmMt8HY4ijV0/edit#gid=1968504951&range=A203) `18010000` which I haven't tested yet
