### ISSUE TITLE
[FR] Starting Class

### ISSUE THREAD

**Issue by ImportTaste** [Ariescyn/EldenRing-Save-Manager#23]
Could you add a feature that lets you change what starting class the character is? (So I can potentially make it so the character doesn't end up with "impossible stats".)

**Comment by Ariescyn** [comment]
Hey there thanks for the work! The classes should be in the main and character headers which are static so that will be straightforward. But even when you load a save and don't change anything, massive amounts of data shift around. If there are other values related to your class and they don't mesh up with the ones in the headers, then I dont know how safe that would be to use online or if there would be discrepancies with your class in-game in certainly situations.

I will take a look tomorrow and do some testing. I'll change the class and send you a save file back if you wanna test anything

**Comment by Ariescyn** [comment]
> Has the starting class feature not yet been committed or is it no longer in the plans? I ask because the issue was closed as 'completed'.

Hey there, sorry i totally forgot about . I went ahead and used your saves to find the index position of the starting class flag.
It's stored 42165 bytes from the start of a character block.

I went ahead and changed a class but i have no idea how to check it in-game. (Haven't played the game much)
Changing the flag won't change your stats etc, I'm curious what purpose this would serve. Can you only do certain quests or get certain items depending on your starting class?

**Comment by Ariescyn** [comment]
I wrote the code to set the character class flag and it will be in the next update. Should i make it more complex and increase the stats of the character to meet minimum stats for that class? Or would that be annoying and intrusive?

I'm honestly questioning whether those few reports of file tampering warnings were actually from the save manager or something else they did because i was walking around with 40,000 hit points while signed in trying to get a ban and got nothing yet.

Either way, I'm not sure if their tampering detection even looks at the starting class flag but the option will be there in the manager now
