### ISSUE TITLE
my save is gone

### ISSUE THREAD

**Issue by FahriBilici** [Ariescyn/EldenRing-Save-Manager#27]
Hello, I used save manager and played for around 3 hours. then quit the game to use save manager again. It didn't detect items I got in that 3 hours. then I entered the game again to check the items.  I saw I am the exact point where I use save manager first time. How can I prevent this or save my progress?

**Comment by jasper1378** [comment]
That's really unfortunate! Using the save manager can be a little confusing to start, but hopefully this will clarify it.

By default, the save manager won't pick up any changes in your saves since the last time you used it. To update the save file stored in the manager with the most recent version,  right click on the name of the save (found on the homescreen of manager) and then click "Update". To summarize the general workflow of using the manager: update the save stored in the manager; make any modifications you want to the save; then click "Load Save" to save those modifications to the actual save file.

I'd also suggest copying/backing up your saves before using the save manager; as it's easy to forget to click "Update" before making modifications to your save file. 

Here's a video made by Ariescyn that outlines how to use the manager: https://www.youtube.com/watch?v=LQxmFuq3dfg

I hope that helps!

**Comment by FahriBilici** [comment]
Actually i just did as you said. But i didnt click update so maybe that caused. So how can i recoger my 3 hours save?

**Comment by jasper1378** [comment]
That's likely the cause your issue then.

I don't know of any way to recover your in-game save if you've overwritten it using the save manager's "Load Save". Perhaps @Ariescyn has some ideas?

**Comment by Ariescyn** [comment]
If you accidentally loaded a save or clicked "update" and had your in-game save overwritten you can use the file recovery tool.

Go to tools > file recovery. You'll see a list of save backups with date and time of creation. The application performs a backup of any save file that was modified or overwritten. You can also select a save backup in the list-box, right-click it and select "Get Info" to see what action was performed before the backup was made. This can assist you in finding the right one.

After you've found you save, select it and click recover. Your recovered saves are located in data/recovery. After that you can simply import them into the save editor again.

**Comment by Ariescyn** [comment]
> That's likely the cause your issue then.
> 
> I don't know of any way to recover your in-game save if you've overwritten it using the save manager's "Load Save". Perhaps @Ariescyn has some ideas?

Also jasper if you want to collaborate on a small project or something let me know! Did some courses for C++ and wanna learn and actually write something lol.

**Comment by jasper1378** [comment]
I didn't realize that the save manager had a built-in file recovery tool. Is that a new feature?

I'd love to collaborate on a project! However, I should warn you that I'm only an amateur programmer myself.
