### ISSUE TITLE
Bug: Importing a save with a steam id set to a number of zeroes corresponding to the length of a steam id

### ISSUE THREAD

**Issue by chozandrias76** [Ariescyn/EldenRing-Save-Manager#28]
As a user
When I set a my save file's steam ID to 00000000000000000
I expect to be able to import it with a different steam ID

Actual result:
<img width="171" alt="image" src="https://user-images.githubusercontent.com/2087677/210184647-712caa0a-6cac-4a98-97e0-aedbc9a71fb8.png">
Shows existing steam id as "0" and hangs when patching

**Comment by chozandrias76** [comment]
The loop here seems to take quite some time:
```py
# hexedit.py:136
for i in id_loc:
            f.seek(0)
            a = f.read(i)
            b = newid.to_bytes(8, "little")
            f.seek(i + 8)
            c = f.read()
            data = a + b + c

            with open(file, "wb") as fh:
                fh.write(data)
```

**Comment by chozandrias76** [comment]
Also when replace_id is passed newid, it is 0 instead of `00000000000000000`
```py
def replace_id(file, newid): # hexedit.py:118
```

**Comment by Ariescyn** [comment]
I had another user report the same thing the other day with import hanging and freezing. When i looked at his save file, it was corrupt and there was no steam id at the static location. So instead of replace_id getting passed a 17 digit number, it was passed 0 (value at static address) instead. 

Basically for whatever reason, if there was a save file with NO steam id at 0x19003B4, it would grab whatever value was there (0).
I modified the replace_id function to validate the static steam id value.

`    with open(file, "rb") as f:
        dat = f.read()
        f.seek(26215348)  # start address of steamID
        steam_id = f.read(8)  # Get steamID
        if len(str(l_endian(steam_id))) != 17: # Prevent save file corruption if steamid is 0 for example.
            return False
`
I'm half awake and not sure what you mean by 

> Also when replace_id is passed newid, it is 0 instead of 00000000000000000 and 1 for 00000000000000001

newid should be a 17 digit number passed in by the user from the GUI

**Comment by chozandrias76** [comment]
> newid should be a 17 digit number passed in by the user from the GUI

Yeah, when I distributed these saves, I tried to anonymize them by changing the Steam ID first. It appears that pythons `int()` conversion, coerces a string `b'00000000000000001'` to `1` and then when you write the entire rest of the file, all of the data is shifted

**Comment by Ariescyn** [comment]
Ahhh I see, so you have save files you want to distribute but don't want your steamid in the files. So you used the manager and changed the steam id to 00000000000000001 or 00000000000000000 and ran into the issue. 

I will fix this on the next update, but in the meantime you could change them to 11111111111111111 without issue

**Comment by chozandrias76** [comment]
Sounds good. Thanks!

**Comment by chozandrias76** [comment]
Looks like you fixed the issue. Thanks!
