### ISSUE TITLE
unstackable items issue?

### ISSUE THREAD

**Issue by Zazcallabah** [Ariescyn/EldenRing-Save-Manager#41]
Hi, I noticed in `ALL_ITEM_IDS.md` it says "Adding weapons and other unstackable items are currently not supported".
What is the specific issue with adding weapons? (I'm just curious)

I know when we mapped the save data for darksouls1 we had separate addresses for equipment and inventory, but also separate [addresses for the equipped items](https://github.com/Zazcallabah/dsfp/blob/master/templates/includes/DarkSouls_PTDE.bt). That was of course many years ago, a lot must have changed since then, but the basic file structure maybe is similar?

**Comment by Ariescyn** [comment]
Hey there, unfortunately i have yet to make sense of how equipment inventory data is stored. Each inventory item entry is 12 bytes long and follows the pattern below for stackable items

{'name': 'Lords Rune', 'item_id': [103, 11], 'uid': [0, 176], 'quantity': 77, 'pad1': [0, 0, 0], 'iter': 138, 'pad2': [0, 0, 0]}

This is in sequential order, so address 100 would be 103, address 101 would be 11, etc. 
The UID should be [0,176] otherwise it's not the right entry
Iter increments every time you add an item to inventory, but when you remove the item, the entry is removed, so the iter will skip ahead in value often. padding is always zeros.

Now if you create a new vagabond character and check its inventory, and view it with the same arrangement as the above, you get the following:

{'name': 'Vagabond Knight Gauntlets', 'item_id': [232, 18], 'uid': [10, 16], 'quantity': 1, 'pad1': [255, 255, 255], 'iter': 138, 'pad2': [1, 0, 0], 'index': 109878}

{'name': 'Vagabond Knight Greaves', 'item_id': [76, 19], 'uid': [10, 0], 'quantity': 255, 'pad1': [255, 255, 255], 'iter': 255, 'pad2': [255, 255, 255], 'index': 42798}

{'name': 'Vagabond Knight Helm', 'item_id': [32, 18], 'uid': [10, 0], 'quantity': 132, 'pad1': [18, 10, 0], 'iter': 232, 'pad2': [18, 10, 0], 'index': 42786}

I can identify the item ID, but it does not follow the same pattern as a stackable item. I've tried changing the item ID but it never works. I've tried items that are equipped or unequipped to no avail. I can't even get arrows to work consistently since the item ID can be different across save files.

I would love some help or a fresh take on this if anyone is interested. I can share the tools i use for grabbing inventory data if needed.

**Comment by Ariescyn** [comment]
I should also note that the start address of inventory data can be different across save files. If you look at the address of the Tarnished Wizened Finger (first item you get), it will be around 43k but different for each file. Also, when you load into the game and immediately exit without saving, massive amounts of data can shift around. This is why i use patterns to find the right addresses since they aren't static

**Comment by Zazcallabah** [comment]
I'm looking in `hexedit.py`, are you only ever _searching_ for the item and stats locations in the file? Is it because they move and dont have fixed addresses? I assume so. Do we know why?

**Comment by Ariescyn** [comment]
I haven't been able to find a way to predict the shifts in data yet, like an offset value or something. Also, even if some value might be static on one save file, it can be at a different address on another save file

**Comment by Zazcallabah** [comment]
I'm pretty sure they would insert the lengths and offsets of the segments into an index somewhere in the file. 

I'm currently trying to figure out if the block immediately after the checksum contains anything like this but having no luck figuring it out.
![010](https://user-images.githubusercontent.com/485339/231077049-88306352-0bae-445e-800f-adb5a5bc8f27.png)

What fromsoft game was released before ER? was it sekiro? ds3? do we know anything about how they did save files there? that could give us a hint i suppose. I would be very surprised if it wasnt BND4 containers at least.

Or if anyone has done a decompile of the ER exe, could we look into how the game parses save data?
