### ISSUE TITLE
Request: Repair Corrupt Character Data

### ISSUE THREAD

**Issue by Davidian1024** [Ariescyn/EldenRing-Save-Manager#50]
Hey there,
First I want to thank you for making this tool.  I think it's the only hope I have in recovering my character.

The game crashed and my save file is now corrupt.  Over 160 hours lost.  I've tried many different things I found online to get it back, and while nothing has worked, your tool can at least see the character data is still in there.

So I tried just fixing the checksums (alot of suggestions for this), all the checksums I found in the file already matched their corresponding data blocks.  So that made no difference.

I tried the trick where you create a brand new save with a brand new character and try to overwrite that character with the character from your corrupted save file.  This works partially.  After starting the game with the new save file with my old character data patched in, I can see it in there as an option to load.  It does still show some aspects of the new character that was overwritten though.  Then, when I try to start the game from this patched save file the game tells me the character is corrupt.

It's frustrating because when I look through my character's details with your tool, it looks like everything is there.  But, I tend to assume that some of the data is actually missing.  But I can't tell what.

I'm wondering if there's a way to identify what's corrupt/missing in my character data and then replace those parts.  Like from a brand new character maybe?  I'm suggesting all this without really understanding the structure of these save files.

Anyway, I was wondering if you had any thoughts on this.  Like, how realistic is any of what I'm suggesting?

**Comment by Ariescyn** [comment]
Hey there, sorry for the late reply. I'm sorry to hear you're save file has been corrupted.
Unfortunately i think you are out of options. Checksums are automatically recalculated when you copy a character so that isn't the solution.

Trying to find specific segments of corrupt data would probably take hundreds of hours in a hex editor, especially since every time you load into a save file (even if you changed nothing) massive amounts of data is shuffled around to different locations with no predictable offset or pattern.
