### ISSUE TITLE
Question: Deleted saves being detected

### ISSUE THREAD

**Issue by ThunderMage** [Ariescyn/EldenRing-Save-Manager#53]
If I delete an old save(s) from my in-game directory, then import the file into Save Manager, it still shows the deleted save in its original slot (slot 1, slot 2, etc.).

I can save over them with newer, clean saves, but I'm concerned that if I go into online mode, my old saves may be detected by the server, or it will know that they've been pasted over, and I'm worried that I'll get banned for it.

What do you think about this?

Edit: I actually just realized I need only turn off steam cloud save updating.

**Comment by Ariescyn** [comment]
You are safe, anything done in the character manager isn't detectable and deleted saves showing up in the save manager still is normal. 

When you delete a character in-game, the game doesn't actually remove the data, it just marks it for deletion so and you can't see it in the game menu anymore. That's why the save manager still sees it. When you create a new character in-game, it will overwrite the deleted character.

This is actually useful to some who accidentally deleted their saves, i even made a tutorial for it: https://youtu.be/32hEaXAY8hU?si=K4Ajq7cCyCsxM7pY

**Comment by ThunderMage** [comment]
Thanks, I appreciate it. I've been adding golden runes directly to the current clean save I made yesterday, instead of editing my level. As long as I consume them, I'm guessing I should still be safe for online mode?

**Comment by Ariescyn** [comment]
You should be fine and that's the safest way. I've been doing it since release without issue. Also there have only been a few reports of bans over 2 years
