### ISSUE TITLE
Question about Checksums

### ISSUE THREAD

**Issue by strawstack** [Ariescyn/EldenRing-Save-Manager#56]
This is just a question and not an actual issue. Awesome tool by the way, it worked great for me. I was wondering how you figured out how to calculate the checksums? Is there a standard for checksums for this type of file, or are they specific to Elden Ring? Thanks

**Comment by Ariescyn** [comment]
Thanks I'm glad it's useful!

Hundreds of hours of poking around in hxd and wrote many python scripts to analyze the data lol.

The checksum is just your Common MD5.

You can see how I calculate, create, convert and write the md5 checksums in the hexedit.py script in the "recalc_checksum" function

**Comment by Ariescyn** [comment]
I should add that within the save file there is an overall checksum value for the entire file, and then there are individual checksums for each character slot block

**Comment by strawstack** [comment]
Nice. Awesome that you built this up from your own analysis! That's impressive. Another question I came across is how come the "set_rune" value function has to search for the old rune value to find the rune value location. Wouldn't the byte offset for the rune value always be the same for every save file and only have to be found once?

**Comment by Ariescyn** [comment]
Haha actually, if you load into a character and make zero changes and exit immediately, massive amounts of data shift around. It's probably to prevent file tampering. So most values float around with no predictable offset or pattern. Unfortunately there are only a handful of static addresses so I had to come up with ways to find locations dynamically.

For example your stats. I had to find the order that they appeared and found that from the starting byte of the first stat, 48 bytes ahead is your character level. So it sums the values ahead of the current index and if that sum -79 (your character lvl is the sum of your stats -79) than it's found the right location. I also filter the data by only selecting that character slot block and it only searches within a certain range (like index 30k to 90k) where I know it will appear, based on many tests of loading into save files as well as testing nexus and user save files

**Comment by Ariescyn** [comment]
Inventory also isn't in the same place after loading into the game once.

I found a pattern of how entries of inventory items appear, an individual entry would look like this (roughly because I don't remember it off the top of my head):

0
0
22
11
0
176
5
43
0
0

00 is padding I guess

22 and 11 is the item id

0 and 176 is a category I'd I believe. Some items can be 128 128 like weapons.

5 is the quantity

And 43 would be the the iterable that increases value after each item as they get added to your inventory. Oddly enough when you use an item or sell it etc, it will remove that entry but not update the iterable, so the sequence can skip values, like 1,2,3,6,7

**Comment by strawstack** [comment]
Thanks for the answers. That's more complicated than I thought. Surprising that the numbers shift around, but cool that you were able to reverse engineer the amount that you have!
