### ISSUE TITLE
How do I delete characters that were deleted in-game?

### ISSUE THREAD

**Issue by jammermt99** [Ariescyn/EldenRing-Save-Manager#57]
My old characters from back when I started playing are showing up. They were clones that I made to beat the tutorial boss. After they died I deleted each and made a new one. How do I delete them for good?

**Comment by Ariescyn** [comment]
When you delete a character in-game, the game doesn't actually delete the data from the save file, instead it marks it for deletion and hides it from the character selection menu. 

Once you create a new character in-game, the game will overwrite that character marked for deletion.

Since the data is still present in the save file, the manager will still see deleted characters.

So you can either make a new character in-game or take a new save file and copy over the characters you want, that way it won't show up in the manager
